version: '2'

checks:
  argument-count:
    enabled: true
    
  complex-logic:
    enabled: true
    
  file-lines:
    enabled: true
    
  identical-code:
    enabled: true
    
  method-complexity:
    enabled: true
    
  method-count:
    enabled: true
    
  method-lines:
    enabled: true
    
  nested-control-flow:
    enabled: true
    
  return-statements:
    enabled: true
    
  similar-code:
    enabled: true
    

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"


exclude_patterns:
- config/
- "**/node_modules/"
- "**/__test__/"
